### ISSUE TITLE
FeatureCollection properties are not applied to generated regions.

### ISSUE THREAD

**Issue by dfrico** [Turfjs/turf-voronoi#2]
So I have a FeatureCollection with (among other data):
```
geometry: { type: "Point", coordinates: […] },
properties: { id, name ... }
```

However, when I do `voronoiPolygons = turf.voronoi(featureCollection)`, I find that every Feature in `voronoiPolygons` has empty properties:

```
geometry: { type: "Polygon", coordinates: […] }
properties: {  }
```
​​​Is it possible to propagate the Features properties to the polygons generated by this method?

**Comment by jrzimmerman** [comment]
Hi @blayhem this is probably not the package you're looking for please check out `@turf/vonoroi`.

@morganherlocker could we archive some of these old repositories?

**Comment by dfrico** [comment]
Sorry, will post on the appropriate repository :)
